# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `yaml-safe_load_stream3` gem.
# Please instead update this file by running `bin/tapioca gem yaml-safe_load_stream3`.


# source://yaml-safe_load_stream3//lib/yaml/safe_load_stream.rb#5
module YAMLSafeLoadStream
  private

  # source://yaml-safe_load_stream3//lib/yaml/safe_load_stream.rb#27
  def raise_if_tags(obj, filename = T.unsafe(nil), doc_num = T.unsafe(nil)); end

  # A safe version of YAML.load_stream.
  # Parses a multi document stream and raises if it tries to instantiate any
  # non-standard classes
  #
  # @param yaml [String] yaml content
  # @param filename [String] filename to be used in exception messages
  # @return [Array] when a block is not given, returns an Array of documents
  # @yield [document] each document in the stream is yielded if a block is given
  #
  # source://yaml-safe_load_stream3//lib/yaml/safe_load_stream.rb#14
  def safe_load_stream(yaml, filename = T.unsafe(nil)); end

  class << self
    # A safe version of YAML.load_stream.
    # Parses a multi document stream and raises if it tries to instantiate any
    # non-standard classes
    #
    # @param yaml [String] yaml content
    # @param filename [String] filename to be used in exception messages
    # @return [Array] when a block is not given, returns an Array of documents
    # @yield [document] each document in the stream is yielded if a block is given
    #
    # source://yaml-safe_load_stream3//lib/yaml/safe_load_stream.rb#14
    def safe_load_stream(yaml, filename = T.unsafe(nil)); end

    private

    # source://yaml-safe_load_stream3//lib/yaml/safe_load_stream.rb#27
    def raise_if_tags(obj, filename = T.unsafe(nil), doc_num = T.unsafe(nil)); end
  end
end
