# Essentially a stock config file provided by minikube,
# slightly adapted to work from inside the cluster itself
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /k8s/ca.crt
    extensions:
    - extension:
        last-update: Mon, 28 Oct 2024 09:43:39 PDT
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: cluster_info
    server: https://kubernetes.default.svc.cluster.local
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Mon, 28 Oct 2024 09:43:39 PDT
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /k8s/client.crt
    client-key: /k8s/client.key