apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: 'homebase'
  labels:
    app: 'homebase'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 'homebase'
  template:
    metadata:
      labels:
        app: 'homebase'
    spec:
      containers:
      - name: 'homebase'
        image: 'homebase:latest'
        imagePullPolicy: 'Never'
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: rails-master-key
              key: key
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        - name: DB_USERNAME
          value: root
        - name: DB_HOST
          value: mysql
        volumeMounts:
        - mountPath: /db
          name: "db-volume"
      volumes:
      - name: "db-volume"
        hostPath:
          path: "/storage/db"
          type: "Directory"
