apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: 'homebase'
  labels:
    app: 'homebase'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 'homebase'
  template:
    metadata:
      labels:
        app: 'homebase'
    spec:
      containers:
      - name: 'homebase'
        image: 'homebase:latest'
        imagePullPolicy: 'Never'
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_MASTER_KEY
          value: c7504929c056948ca1cc76c85ee4def8
